### ISSUE TITLE
Add `.clang-tidy` config

### ISSUE THREAD

**Issue by deiuch** [slang-project/SLang-Codegen-LLVM#18]
We prefer Google C++ Style Guide.

Example:
https://github.com/googleapis/google-cloud-cpp/blob/main/.clang-tidy

**Comment by deiuch** [comment]
```yaml
---
Checks: >
  -*,
  bugprone-*,
  google-*,
  misc-*,
  modernize-*,
  performance-*,
  portability-*,
  readability-*
WarningsAsErrors: "*"
CheckOptions:
  - key:             readability-identifier-naming.ClassCase
    value:           CamelCase
  - key:             readability-identifier-naming.EnumCase
    value:           CamelCase
  - key:             readability-identifier-naming.FunctionCase
    value:           camelBack
  - key:             readability-identifier-naming.MemberCase
    value:           CamelCase
  - key:             readability-identifier-naming.ParameterCase
    value:           CamelCase
  - key:             readability-identifier-naming.UnionCase
    value:           CamelCase
  - key:             readability-identifier-naming.VariableCase
    value:           CamelCase
  - key:             readability-identifier-naming.IgnoreMainLikeFunctions
    value:           1
```
